"""
End-to-end regression for the auto-strength escalation path.

Creates three images:
    * a "plain" photo-like image with no provenance metadata
    * a JPEG whose EXIF `Software` tag identifies it as Google Imagen
    * an MP4 whose container-level `encoder` tag identifies it as Veo

Then runs `clean_file_v2(auto_strength=True)` on each and asserts:
    - the detector surfaces the expected origin label
    - the plain file keeps `near_lossless`
    - the Google / Veo files escalate to `medium`
    - the cleaned outputs carry no EXIF/container tags
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile

import numpy as np
from PIL import Image, ExifTags

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from origin_detect import detect_origin  # noqa: E402
from watermark_remover import clean_file_v2  # noqa: E402


def _make_photo(path: str, w: int = 768, h: int = 512) -> None:
    rng = np.random.default_rng(42)
    base = rng.integers(0, 255, (h, w, 3), dtype=np.uint8)
    y, x = np.mgrid[0:h, 0:w]
    r = (x / w * 200 + 30).astype(np.uint8)
    g = (y / h * 200 + 30).astype(np.uint8)
    b = ((x + y) / (w + h) * 200 + 30).astype(np.uint8)
    grad = np.dstack([r, g, b])
    img_arr = (0.6 * grad + 0.4 * base).astype(np.uint8)
    Image.fromarray(img_arr, "RGB").save(path, "JPEG", quality=95)


def _tag_id(name: str) -> int | None:
    for k, v in ExifTags.TAGS.items():
        if v == name:
            return k
    return None


def _write_exif_software(path: str, software: str, artist: str = "") -> None:
    im = Image.open(path).convert("RGB")
    exif = im.getexif()
    sw = _tag_id("Software")
    ar = _tag_id("Artist")
    if sw is None:
        raise RuntimeError("Software EXIF tag id not found")
    exif[sw] = software
    if artist and ar is not None:
        exif[ar] = artist
    im.save(path, "JPEG", quality=95, exif=exif.tobytes())


def _probe_tags(path: str) -> dict:
    proc = subprocess.run(
        ["ffprobe", "-v", "error", "-show_format", "-show_streams",
         "-print_format", "json", path],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return {}
    try:
        return json.loads(proc.stdout or "{}")
    except Exception:
        return {}


def _make_veo_mp4(path: str, seconds: int = 1) -> None:
    """Synthesize a small mp4 whose encoder tag says Veo."""
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc=size=640x360:rate=24:duration={seconds}",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "veryfast",
        "-c:a", "aac", "-b:a", "96k",
        "-metadata", "encoder=Google Veo 2",
        "-metadata", "comment=generated by com.google.veo",
        path,
    ]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def run():
    passes = 0
    failures = []

    with tempfile.TemporaryDirectory() as tmp:
        in_dir = os.path.join(tmp, "in")
        out_dir = os.path.join(tmp, "out")
        os.makedirs(in_dir)
        os.makedirs(out_dir)

        plain_jpg = os.path.join(in_dir, "photo.jpg")
        imagen_jpg = os.path.join(in_dir, "gemini_shot.jpg")
        veo_mp4 = os.path.join(in_dir, "veo_clip.mp4")

        _make_photo(plain_jpg)
        _make_photo(imagen_jpg)
        _write_exif_software(imagen_jpg,
                             software="Google Imagen 3 / Gemini 2.5",
                             artist="com.google.gemini")

        _make_veo_mp4(veo_mp4)

        # --- detector checks ------------------------------------------------
        cases = [
            (plain_jpg, False, None),
            (imagen_jpg, True, "google_synthid_image"),
            (veo_mp4, True, "google_synthid_video"),
        ]
        for path, want_robust, want_label in cases:
            rep = detect_origin(path)
            name = os.path.basename(path)
            ok = rep.likely_robust_watermark == want_robust and (
                want_label is None or want_label in rep.matches)
            if ok:
                passes += 1
                print(f"PASS  detect  {name}  robust={rep.likely_robust_watermark}"
                      f"  matches={rep.matches}")
            else:
                failures.append(f"detect({name}): expected robust={want_robust} "
                                f"label={want_label}, got robust={rep.likely_robust_watermark} "
                                f"matches={rep.matches}")

        # --- escalation checks ---------------------------------------------
        clean_cases = [
            (plain_jpg, "near_lossless", False),
            (imagen_jpg, "medium", True),
            (veo_mp4, "medium", True),
        ]
        for path, want_strength, want_esc in clean_cases:
            rep = clean_file_v2(path, out_dir, strength="near_lossless",
                                use_diffusion=False, auto_strength=True)
            name = os.path.basename(path)
            if rep.strength_used == want_strength and rep.auto_escalated == want_esc:
                passes += 1
                print(f"PASS  clean   {name}  strength={rep.strength_used}"
                      f"  escalated={rep.auto_escalated}")
                print(f"              detail: {rep.detail}")
            else:
                failures.append(
                    f"clean({name}): expected strength={want_strength} "
                    f"escalated={want_esc}, got {rep.strength_used} / "
                    f"{rep.auto_escalated}"
                )

            # Output must exist and be non-empty.
            if not (os.path.exists(rep.output_path) and
                    os.path.getsize(rep.output_path) > 0):
                failures.append(f"clean({name}): output missing or empty at {rep.output_path}")
            else:
                passes += 1

            # Output must have no provenance strings from the original.
            post = detect_origin(rep.output_path)
            if post.likely_robust_watermark:
                failures.append(
                    f"clean({name}): output still flagged as robust watermark "
                    f"by detector: matches={post.matches}"
                )
            else:
                passes += 1
                print(f"PASS  strip   {name}  post-matches={post.matches or '[]'}")

        # --- auto off honours manual strength ------------------------------
        rep = clean_file_v2(imagen_jpg, out_dir, strength="near_lossless",
                            use_diffusion=False, auto_strength=False)
        if rep.strength_used == "near_lossless" and not rep.auto_escalated:
            passes += 1
            print("PASS  auto-off keeps manual strength on Imagen input")
        else:
            failures.append("auto-off did not honour manual strength")

    print()
    print(f"Passes: {passes}")
    if failures:
        print(f"Failures: {len(failures)}")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    print("ALL GREEN")


if __name__ == "__main__":
    run()
