"""
Build a proper macOS application bundle for Scrub and (optionally) install
it into /Applications so it shows up in Spotlight, Launchpad, and the Dock.

Layout of the produced bundle:

    Scrub.app/
      Contents/
        Info.plist
        MacOS/
          Scrub                  <- tiny Mach-O stub (Spotlight-compatible)
          Scrub-inner.sh         <- bash launcher (+x)
        Resources/
          AppIcon.icns

The inner launcher calls Homebrew Python + venv site-packages (see script)
from the project directory
that was current when this script was run — i.e. it points at the code
in-place rather than copying it. That way edits to tk_app.py take effect
instantly, with no rebuild step.

Logs go to ~/Library/Logs/Scrub.log so that launch failures are debuggable.

Usage:
    python scripts/build_app.py              # builds build/Scrub.app
    python scripts/build_app.py --install    # also copies to /Applications
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD_DIR = os.path.join(ROOT, "build")
APP_DIR = os.path.join(BUILD_DIR, "Scrub.app")
INSTALL_DIR = os.path.join(os.path.expanduser("/Applications"), "Scrub.app")


LAUNCHER = """#!/bin/bash
# Scrub-inner.sh - generated by scripts/build_app.py.
# Routes all output to ~/Library/Logs/Scrub.log so Dock/Spotlight launches
# are debuggable.
set -u
shopt -s nullglob

PROJECT_DIR="__PROJECT_DIR__"
LOG_DIR="$HOME/Library/Logs"
LOG_FILE="$LOG_DIR/Scrub.log"
mkdir -p "$LOG_DIR"

# GUI apps launched by Dock/Spotlight inherit a stripped PATH
# (/usr/bin:/bin:/usr/sbin:/sbin) that does NOT include Homebrew. Make sure
# ffmpeg / ffprobe and any other CLI dependency shipped via Homebrew can be
# found. We prepend the common install prefixes; harmless if they don't exist.
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"

cd "$PROJECT_DIR" || {
  /usr/bin/osascript -e 'display alert "Scrub" message "Project folder missing. Re-run scripts/build_app.py."'
  exit 2
}

# Do not use .venv/bin/python for Dock/Spotlight launches: its startup loads
# site.py which reads .venv/pyvenv.cfg under Desktop/Experiments. macOS
# privacy (TCC) often denies GUI apps access there, causing:
#   PermissionError: Operation not permitted: .../pyvenv.cfg
# Use Homebrew Python with the same X.Y as the venv and add site-packages
# via PYTHONPATH instead.
PY=""
SITE=""
PY_WANT=""
for _lib in "$PROJECT_DIR"/.venv/lib/python*; do
  if [ -d "$_lib/site-packages" ]; then
    SITE="$_lib/site-packages"
    PY_WANT=$(basename "$_lib" | sed 's/^python//')
    break
  fi
done

if [ -n "$SITE" ] && [ -n "$PY_WANT" ]; then
  for _try in "/opt/homebrew/bin/python${PY_WANT}" "/usr/local/bin/python${PY_WANT}"; do
    if [ -x "$_try" ]; then
      _got=$("$_try" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null) || continue
      if [ "$_got" = "$PY_WANT" ]; then PY="$_try"; break; fi
    fi
  done
fi

unset PYTHONHOME
if [ -n "$PY" ] && [ -n "$SITE" ]; then
  {
    echo "[Scrub] $(date '+%Y-%m-%d %H:%M:%S') starting with $PY + site-packages (not .venv/bin/python)"
  } >>"$LOG_FILE"
  export PYTHONPATH="$PROJECT_DIR:$SITE${PYTHONPATH:+:$PYTHONPATH}"
  exec "$PY" "$PROJECT_DIR/tk_app.py" >>"$LOG_FILE" 2>&1
fi

# Fallback: venv interpreter (OK from Terminal; may fail from Finder).
if [ -x "$PROJECT_DIR/.venv/bin/python" ]; then
  exec "$PROJECT_DIR/.venv/bin/python" "$PROJECT_DIR/tk_app.py" >>"$LOG_FILE" 2>&1
fi

/usr/bin/osascript -e 'display alert "Scrub" message "Could not start Python. Install Homebrew python@3.12 and python-tk@3.12, then in the project folder run: python3 -m venv .venv && pip install -r requirements.txt && python3 scripts/build_app.py --install. Details: ~/Library/Logs/Scrub.log"'
exit 3
"""


def _write_info_plist(path: str) -> None:
    plist = {
        "CFBundleName":                "Scrub",
        "CFBundleDisplayName":         "Scrub",
        "CFBundleIdentifier":          "com.scrub.app",
        "CFBundleVersion":             "1.0",
        "CFBundleShortVersionString":  "1.0",
        "CFBundlePackageType":         "APPL",
        "CFBundleSignature":           "????",
        "CFBundleExecutable":          "Scrub",
        "CFBundleIconFile":            "AppIcon",
        "LSMinimumSystemVersion":      "12.0",
        "LSApplicationCategoryType":   "public.app-category.utilities",
        "NSHighResolutionCapable":     True,
        "NSRequiresAquaSystemAppearance": False,
        # Don't request any network / camera / etc. entitlements; this is a
        # pure local tool. The only external I/O is user-picked files.
    }
    with open(path, "wb") as f:
        plistlib.dump(plist, f)


def _ensure_icon() -> str:
    icns = os.path.join(BUILD_DIR, "Scrub.icns")
    if os.path.exists(icns):
        return icns
    print(">> building Scrub.icns (running scripts/make_icon.py)")
    subprocess.run([sys.executable, os.path.join(HERE, "make_icon.py")],
                   check=True)
    if not os.path.exists(icns):
        raise RuntimeError("Scrub.icns missing after make_icon.py")
    return icns


def _compile_mach_o_stub(mac_os_dir: str) -> bool:
    """Build Contents/MacOS/Scrub as a real Mach-O binary. Returns False if clang is missing."""
    src = os.path.join(HERE, "scrub_launcher.c")
    dst = os.path.join(mac_os_dir, "Scrub")
    if not os.path.isfile(src):
        return False
    try:
        subprocess.run(
            ["clang", "-O2", "-Wall", "-Wextra", "-o", dst, src],
            check=True, capture_output=True, text=True,
        )
        os.chmod(dst, 0o755)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        err = getattr(e, "stderr", None) or str(e)
        print(f">> could not build Mach-O stub (clang): {err}")
        print(">> install Xcode Command Line Tools: xcode-select --install")
        return False


def _codesign_ad_hoc(app_dir: str) -> None:
    """Ad-hoc sign the bundle so Gatekeeper / Launch Services accept it."""
    subprocess.run(
        ["codesign", "--force", "--deep", "--sign", "-", app_dir],
        check=False, capture_output=True, text=True,
    )


def build(force: bool = False) -> str:
    if force and os.path.exists(APP_DIR):
        shutil.rmtree(APP_DIR)
    os.makedirs(os.path.join(APP_DIR, "Contents", "MacOS"), exist_ok=True)
    os.makedirs(os.path.join(APP_DIR, "Contents", "Resources"), exist_ok=True)

    icns = _ensure_icon()
    shutil.copy2(icns, os.path.join(APP_DIR, "Contents", "Resources", "AppIcon.icns"))

    mac_os = os.path.join(APP_DIR, "Contents", "MacOS")
    inner_path = os.path.join(mac_os, "Scrub-inner.sh")
    with open(inner_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(LAUNCHER.replace("__PROJECT_DIR__", ROOT))
    os.chmod(inner_path, 0o755)

    stub_ok = _compile_mach_o_stub(mac_os)
    if not stub_ok:
        # Last resort: shell script as main executable (Spotlight may still fail).
        fallback = os.path.join(mac_os, "Scrub")
        try:
            if os.path.lexists(fallback):
                os.remove(fallback)
        except OSError:
            pass
        shutil.copyfile(inner_path, fallback)
        os.chmod(fallback, 0o755)
        try:
            os.remove(inner_path)
        except OSError:
            pass

    _write_info_plist(os.path.join(APP_DIR, "Contents", "Info.plist"))

    _codesign_ad_hoc(APP_DIR)

    # Touch the bundle so LaunchServices re-registers it.
    subprocess.run(["touch", APP_DIR], check=False)
    return APP_DIR


def install(app_path: str) -> str:
    """Install into /Applications, replacing any previous copy."""
    if os.path.exists(INSTALL_DIR):
        # Remove the old bundle. rm -rf to handle nested perms gracefully.
        subprocess.run(["rm", "-rf", INSTALL_DIR], check=True)

    # ditto preserves metadata/permissions better than plain cp.
    try:
        subprocess.run(["/usr/bin/ditto", app_path, INSTALL_DIR], check=True)
    except Exception:
        shutil.copytree(app_path, INSTALL_DIR)

    # Strip the quarantine xattr so Gatekeeper doesn't demand verification
    # on first launch.
    subprocess.run(
        ["xattr", "-dr", "com.apple.quarantine", INSTALL_DIR],
        check=False, capture_output=True,
    )
    # Ask LaunchServices to register the new app (shows up in Spotlight
    # and Launchpad immediately on modern macOS).
    lsregister = (
        "/System/Library/Frameworks/CoreServices.framework/Versions/A/"
        "Frameworks/LaunchServices.framework/Support/lsregister"
    )
    if os.path.exists(lsregister):
        subprocess.run([lsregister, "-f", INSTALL_DIR],
                       check=False, capture_output=True)
    return INSTALL_DIR


def main():
    ap = argparse.ArgumentParser(description="Build/install the Scrub .app bundle.")
    ap.add_argument("--install", action="store_true",
                    help="copy the built bundle to /Applications")
    ap.add_argument("--force", action="store_true",
                    help="rebuild even if Scrub.app already exists")
    args = ap.parse_args()

    app = build(force=args.force)
    print(f"built  {app}")

    if args.install:
        dst = install(app)
        print(f"installed to  {dst}")
        print("Open with: Spotlight (⌘-space) → \"Scrub\"")


if __name__ == "__main__":
    main()
